// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6Q_8a4TocdAomv_GlOSfAno_2mYSwW0',
    appId: '1:462131117227:web:b84d7d47e2ef6039044bee',
    messagingSenderId: '462131117227',
    projectId: 'appmobile-flutterdart-83764',
    authDomain: 'appmobile-flutterdart-83764.firebaseapp.com',
    storageBucket: 'appmobile-flutterdart-83764.firebasestorage.app',
    measurementId: 'G-4CR2SEK2BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYVfd6vgXbiHIAYcuC4HeBOoinKsWmgCQ',
    appId: '1:462131117227:android:db1f65b3302a8039044bee',
    messagingSenderId: '462131117227',
    projectId: 'appmobile-flutterdart-83764',
    storageBucket: 'appmobile-flutterdart-83764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4djg_szlBlUvtQ9xNtBQprHdNExFlqGE',
    appId: '1:462131117227:ios:27cfc5601731b65b044bee',
    messagingSenderId: '462131117227',
    projectId: 'appmobile-flutterdart-83764',
    storageBucket: 'appmobile-flutterdart-83764.firebasestorage.app',
    iosBundleId: 'com.example.appMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4djg_szlBlUvtQ9xNtBQprHdNExFlqGE',
    appId: '1:462131117227:ios:27cfc5601731b65b044bee',
    messagingSenderId: '462131117227',
    projectId: 'appmobile-flutterdart-83764',
    storageBucket: 'appmobile-flutterdart-83764.firebasestorage.app',
    iosBundleId: 'com.example.appMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK6Q_8a4TocdAomv_GlOSfAno_2mYSwW0',
    appId: '1:462131117227:web:954bbfbc2b90bc7b044bee',
    messagingSenderId: '462131117227',
    projectId: 'appmobile-flutterdart-83764',
    authDomain: 'appmobile-flutterdart-83764.firebaseapp.com',
    storageBucket: 'appmobile-flutterdart-83764.firebasestorage.app',
    measurementId: 'G-CWTHN4WM0C',
  );
}
